server:
  port: 8082

spring:
  application:
    name: METRICS-CONSUMER

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  sql:
    init:
      mode: always

  kafka:
    consumer:
      bootstrap-servers: http://kafka:29092

message.topic.name: metrics-topic
message.topic.name.dlt: metrics-topic.DLT

logging:
  level:
    com:
      example: debug
    org:
      springframework:
        orm:
          jpa: info
        transaction: info
        web: info